language: go

go:
  - "1.9.x"
  - "1.12.x"

env:
  matrix:
    - STAGE=testredis
    - STAGE=testconn
    - STAGE=testcluster

before_install:
  - make redis-server/redis-server

cache:
  directories:
    - $HOME/redis-server

install:
  - go get -t -v ./...

script: make $STAGE
